import time
from selenium import webdriver
driver = webdriver.Chrome("../tools/chromedriver.exe")
windows = driver.window_handles
try:
    # 管理员登陆
    driver.implicitly_wait(5)
    driver.get("http://192.101.1.28:8088/upload/forum.php")
    list_window=driver.current_window_handle
    driver.switch_to_window(list_window)#激活窗口
    username = driver.find_element_by_id('ls_username')
    username.send_keys('admin')
    time.sleep(2)
    password = driver.find_element_by_id('ls_password')
    password.send_keys('haotest')
    time.sleep(2)
    password.submit()
    time.sleep(4)
    print("管理员登陆成功")

    #进入默认板块，删除帖子
    # mrbk = driver.find_element_by_css_selector("#category_1 > table > tbody > tr:nth-child(1) > td:nth-child(2) > h2 > a")
    # mrbk.click()
    # print("默认板块")
    # xfk = driver.find_element_by_css_selector("#normalthread_9 > tr > td.o")
    # xfk.click()
    # print("选小框框")
    # sc = driver.find_element_by_css_selector("#mdly > p:nth-child(6) > strong:nth-child(1) > a")
    # sc.click()
    # print("删除")
    # qd = driver.find_element_by_css_selector("#modsubmit > span")
    # qd.click()
    # print("确定")

#进入版块管理(管理中心--论坛)
    glzx = driver.find_element_by_css_selector("#um > p:nth-child(2) > a:nth-child(15)")
    glzx.click()
    print("进入管理中心")
    # time.sleep(5)
    driver.switch_to.window(driver.window_handles[1])
    tj = driver.find_element_by_name("admin_password")
    tj.send_keys('haotest')
    lt=driver.find_element_by_name("submit")
    lt.click()
    time.sleep(3)
    djlt = driver.find_element_by_id("header_forum")
    djlt.click()
    print("进入论坛成功")
    driver.switch_to.frame("main")#切换到iframe
    tjxmk=driver.find_element_by_css_selector("#cpform tbody:nth-child(3) td:nth-child(2) a")
    tjxmk.click()
    print("tianjian")
    tjb=driver.find_element_by_css_selector("#submit_editsubmit")
    tjb.click()
    print("提交成功")
    driver.close()
    driver.switch_to.window(driver.window_handles[0])
    hdlt=driver.find_element_by_css_selector('#pt > div > a:nth-child(3)')
    hdlt.click()
    tc=driver.find_element_by_css_selector("#um > p:nth-child(2) > a:nth-child(17)")
    tc.click()
    xyh=driver.find_element_by_name("username")
    xyh.send_keys("zhaoyanyan")
    mma=driver.find_element_by_id("ls_password")
    mma.send_keys("haotest")
    dla=driver.find_element_by_css_selector("#lsform > div > div > table > tbody > tr:nth-child(2) > td.fastlg_l > button > em")
    dla.click()
    print("登陆上了")
    xbkft=driver.find_element_by_css_selector("#category_1 > table > tbody > tr:nth-child(2) > td:nth-child(2) > h2 > a")
    xbkft.click()
    print("点击新板块成功")
    xrft=driver.find_element_by_id("subject")
    xrft.send_keys("艳艳66666666")
    xrnr=driver.find_element_by_name("message")
    xrnr.send_keys("嘿嘿")
    fb=driver.find_element_by_css_selector("#fastpostsubmit > strong")
    fb.click()
    print("发表了")
    hftt=driver.find_element_by_name("fastpostmessage")
    hftt.send_keys("小仙女")
    ttjj=driver.find_element_by_css_selector("#fastpostsubmit > strong")
    ttjj.click()
    


finally:
    driver.quit()
